version: '3.8'

services:
  api1:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=db1
      - DB_USER=admin
      - DB_PASSWORD=db4dev$
      - DB_NAME=devdb
      - PORT=8081
    depends_on:
      - db1

  api2:
    build: .
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=db2
      - DB_USER=admin
      - DB_PASSWORD=db4test$
      - DB_NAME=testdb
      - PORT=8082
    depends_on:
      - db2

  db1:
    image: postgres:14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=db4dev$
      - POSTGRES_DB=devdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db1_data:/var/lib/postgresql/data

  db2:
    image: postgres:14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=db4test$
      - POSTGRES_DB=testdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db2_data:/var/lib/postgresql/data

volumes:
  db1_data:
  db2_data:
